### PR TITLE
Add EVM3* trimmers

### PR DESCRIPTION
**Pull request by yaqwsx**
SMD trimmer footprints are missing from the library. I added footprints according this datasheet: http://www.datasheets360.com/pdf/69486460378724719
vystrizek
vystrizek

### CODE REVIEW

**Comment by yaqwsx** [comment]
No activity?

**Comment by pointhi** [comment]
I think this should be added to https://github.com/KiCad/Potentiometers.pretty

**Comment by yaqwsx** [comment]
Should I move it right away or is this a question for other maintainer?

**Comment by pointhi** [comment]
I think you should move them. There are no trimmers in this Repository, and I don't think it's intended to do so.

**Comment by yaqwsx** [comment]
Moved, PR: KiCad/Potentiometers.pretty#13

**Pull request closed without merging**
