### PR TITLE
Create RK73HE1.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
0402 footprint for manufacturer KOA, RK73HE1 series, following their datasheet.
Important to have correct footprint to avoid tombstone problems at reflow.

### CODE REVIEW

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by hackscribble** [comment]
Hi @savenlid 

Sorry your pull request got forgotten for so long. 

Is this the correct datasheet for the footprint dimensions?  http://www.koaspeer.com/pdfs/Appendix_E.pdf

Thanks

**Comment by savenlid** [comment]
Hi

Yes, correct.

I would like take the oportunity to point out that many times a
solder-paste shape needs to be different than its solder pad shape.

this notion that you can only make a reduction or increase of the
solder-paste based on the pad-shape needs to be broken. (snap out of it)

For optimal EMS  yield the pad , solder-paste and solder mask should be
able to be made in in independent free form polygons.

one paper among many that touches upon the subject:

http://prod.semicontaiwan.org/zh/sites/semicontaiwan.org/files/data15/docs/7_5_semicon_taiwan_2015_ppt_senju_akita.pdf

thanks
/Nicholas



2017-07-10 12:39 GMT+02:00 Hackscribble <notifications@github.com>:

**Comment by hackscribble** [comment]
> I would like take the oportunity to point out that many times a
solder-paste shape needs to be different than its solder pad shape.

Does that apply to this component? I don't see it mentioned in that datasheet.

**Comment by savenlid** [comment]
nope, does not


2017-07-10 13:15 GMT+02:00 Hackscribble <notifications@github.com>:

**Comment by savenlid** [comment]
for 0201 it will

maybe not in this datasheet but highly recommended


2017-07-10 13:18 GMT+02:00 Nicholas Sävenlid <nicholas@savenlid.se>:

**Comment by poeschlr** [comment]
> maybe not in this datasheet but highly recommended

link?

**Comment by savenlid** [comment]
this one recommends the square openings for solder-paste for BGA

http://www.cypress.com/file/45826/download

and if you google you will see many recommend that for pitch < 1.00mm bga

page 25 example:
http://www3.uic.com/wcms/Images.nsf/c06db59d70a043cc85256809004d8cbe/f7823928481e2b50852569960071b710/$FILE/0201Webcast14Sept2000.PDF


2017-07-10 15:54 GMT+02:00 Rene Pöschl <notifications@github.com>:

**Comment by poeschlr** [comment]
I don't see anything in there that can not be achieved with kicad. Simply remove paste from the main pad and add a paste only pad with the size you want. (As we already do for many exposed pads in example the qfn repo.) Polygon pads might come in kicad v5 (if it gets finished early enough) otherwise we will need to wait until v6

**Comment by savenlid** [comment]
Yes.
Thanks for the tip.
It's doable.

Let's pray for polygons in v5.
They will solve other problems.
I don't think they even have been released in Nightly yet.
It's very sad for me personally.
I want them very much.


Den 10 juli 2017 16:20 skrev "Rene Pöschl" <notifications@github.com>:

**Comment by poeschlr** [comment]
Well if you want something, get in touch with the developer who is currently implementing it and help them. I bet they would like support for testing and documenting. (Be the change you want to see.)

**Comment by savenlid** [comment]
I did try do do as you said,

But to do 1 single pad with round pad and square solder is impossible.
Thats what i try to say that shapes should be independent. (but still kept
within 1 single pad-entity)

I had to make 2 separate pads on top of each other with same pad#.
One round pad and a square solder-paste.

So yes, its doable but not pretty.


also for bga you need to "hard-code" the solder-mask, you cannot loose
control of that.




2017-07-10 18:34 GMT+02:00 Rene Pöschl <notifications@github.com>:

**Comment by poeschlr** [comment]
you can do that by either using a third solder mask only pad if it also has a different shape or by either setting the mask clearance in the pad or footprint settings. (footprint settings if all pads need the same clearance, pad settings if specific pads differ)

Yes sadly this is not done for all bga footprints. (I remember to have merged a few where it has been done correctly.)
Would you care to fix the bga lib? (remember that we still only allow wrl 3d file paths because of backwards compatibility.)

**Comment by savenlid** [comment]
The kicad bga lib ?

I may do if i find the time.

what do you want to fixed ?

square solder on <= 0.8mm pitch bga:s ?
fixed soldermask +0.05 radius ?





2017-07-11 11:09 GMT+02:00 Rene Pöschl <notifications@github.com>:

**Comment by poeschlr** [comment]
It might depend on the footprint. I don't really know the state of the bga lib. I fear it might be quite inconsistent.
Everything that is fixed, will help.

**Comment by poeschlr** [comment]
By the way: such a communication might be better suited for an issue in the correct repo. (This way everyone knows where to look for. I will open an issue and make a tldr version of our discussion.)

**Comment by evanshultz** [comment]
Thanks @savenlid for volunteering to help on this. If you're making a different stencil opening shape than the pad shape, please make the pad with a pin number be on the F.Cu and F.Mask layer (assuming an SMT pad), while the stencil opening pad does not have a pin number and is only on the F.Paste layer. You can see some examples of the Cree LED footprints at https://github.com/KiCad/LEDs.pretty.

**Comment by hackscribble** [comment]
Hi @savenlid should the different paste opening be applied to this footprint as well?  Or should I review it as is?  Thanks

**Comment by savenlid** [comment]
this is a 0402, so it does not require any special paste offset or size.
It's for 0201 and  smaller resistors.


That may change in the very near future, because:

Historically the EMS has always shrunk the paste openings by about 10% as a
rule of thumb and that has been applied allover the PCB on every single
component.

This is no-longer a viable solution as it will hit smaller geometries into
bad yield.

I foresee that we are moving into a situation where this
solder-paste-shrinking will need to be moved from EMS/Stencil manufacturer
into the actual footprint.
Its the only reasonable solution for quality, because a manual selection of
what to shrink and not to shrink will be subject to human error and is not
a 100% repeatable process.

Very soon this 0402 probably will have to be redesigned with -10% paste.




2017-07-12 13:40 GMT+02:00 Hackscribble <notifications@github.com>:

**Comment by hackscribble** [comment]
Ok, thanks.  Looking at the RK73H1E footprint, there are a few review points.

1. For consistency with KLC, please change the footprint name to `KOA_RK73H1E_NoSilk`.  The file name should be `KOA_RK73H1E_NoSilk.kicad_mod`.

2. The standard 0402 resistor 3D model is closer to the RK73H1E than the capacitor currently referenced.  
 - To use the resistor model, change the reference to `${KISYS3DMOD}/Resistors_SMD.3dshapes/R_0402.wrl`.  

- The alternative would be `${KISYS3DMOD}/Resistors_SMD.3dshapes/KOA_RK73H1E.wrl` in case you or someone else wants to produce a more accurate model.

3. KLC sets solder mask clearance to 0 unless required otherwise by the manufacturer.  The footprint has it set to 0.1mm.  Is that a KOA (or other) recommendation?
 
4. Please check the KLC 7.3 and 7.4 errors being flagged in the Travis CI checks (link below).
 
Many thanks

**Comment by evanshultz** [comment]
@savenlid My understanding from the conversation above is that 0402s are OK now, and that this footprint does not comply with KLC. If you are not going to make the changes necessary to merge this footprint into the official KiCad repo, please close this PR.

**Comment by savenlid** [comment]
https://github.com/savenlid/kicad

**Pull request closed without merging**
