### PR TITLE
Added more, KLC checked smd resistors.

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by michal777** [comment]
There is wrong description, wrong silkscreen, if 3d model doesn't exist it should be removed from footprint file, there are wrong indentations in the files.

**Comment by crackerizer** [comment]
Fixed.

**Comment by michal777** [comment]
Is the land pattern for 1812 correct? ERJ3GEYJ101V is 0603. In this datasheet http://industrial.panasonic.com/lecs/www-data/pdf/AOA0000/AOA0000PE36.pdf on page 19 land pattern for ERJ12 is defined.
Courtyard is not rounded to 0.05 mm and a bit too high (should be 0.25 mm measured from components body and from pads.

**Comment by crackerizer** [comment]
Thank you for rechecking that. It's now fixed.

**Pull request merged**
